spring:
  application:
    name: VUchobe
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
---
server:
  port: 8082


spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 32AschyeS2463xzv
#logging:
#  level: 
#    root: debug
---
server:
  port: 8082

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://dbpostgress:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 32AschyeS2463xzv
